### ISSUE TITLE
好像Jar里打进了v7的文件，冲突的不要不要的，求解决，非常感谢

### ISSUE THREAD

**Issue by OCTSJimmy** [smuyyh/BubblePopupWindow#2]
好像Jar里打进了v7的文件，冲突的不要不要的，求解决，非常感谢

**Comment by smuyyh** [comment]
jar？ 依赖的时候把v7 exclude掉

**Comment by OCTSJimmy** [comment]
后来解决了，问题产生的原因在于自定义属性attrs中，shadowColor、padding、strokeWidth、cornerRadius有同名属性。加了个前缀搞定。
